name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Your Docker Hub username stored in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Your Docker Hub password or access token stored in secrets

    # Step 3: Build and Push Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .  # Build from the current directory
        push: true  # Push the image to the registry
        tags: ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest  # Tag the image with your Docker Hub username and desired image name
