name: Build Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Build Docker image
    - name: Build Docker Image
      run: |
        docker build -t dockerfile:latest .  
    # Build the Docker image locally in the GitHub Actions runner
